name: Gerador de CHANGELOG

# só executa no push de commit da branch main
on:
  push:
    branches:
      - main

jobs:
  build:
    # só deixa executar se o último commit não conter 'skip ci' na mensagem
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # instala a versão 11.x do Node.js
      - name: Instala o Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # instala as dependências, vai para a master
      # executa o standard-version, e envia o commit e tag
      - name: Gera o CHANGELOG
        run: |
          npm ci
          git checkout main
          npm run release
          git push origin main --follow-tags
